# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b1f272434a123a5332ac6e1e5f71180a857cceab09d2e68447657b76e4c4bab4abda0536bf9c3e4bc83bb72ca3644f2d00e3e39d21105f5aa37e20bb6bd0a1f

test:
  secret_key_base: 141237264c679914c5f0f51c22245ac6316e144b80a8f8f121fef27e5a433cbe90ce94f146cafde0511d25d501419a2a1e2795901c202bf2272bd957938bd601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
